apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iosmcn-core-router 
  namespace: iosmcncore
spec:
  interval: 1m
  chart:
    spec:
      chart: ./router
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: iosmcn-core-router-gitrepo
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: iosmcncore
  valuesFrom:
  - kind: ConfigMap
    name: iosmcn-core-router-values
    valuesKey: values.yaml

