apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: iosmcn-core-gitrepo
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/varun-chandramouli/ios-mcn-core-helm-chart
  ref:
    branch: nephio-deploy-test
  secretRef:
    name: iosmcn-github-auth
  ignore: |
    /*
    !/router/**
